config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get 'signup', to: 'users#new' 
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    flash[:alert] = 'You must be logged in to perform that action.'
    redirect_to login_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully.'
      redirect_to user
    else
      flash.now[:alert] = 'You entered incorrect email or password.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out.'
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update destroy]

  def show; end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to FORMS #{@user.username}, you have successfully signed up."
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account information was successfully updated.'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Account and all associated articles successfully deleted.'
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    return unless current_user != @user && !current_user.admin?

    flash[:alert] = 'You can only edit or delete your own account.'
    redirect_to @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'circle shadow mx-auto d-block')
  end
end

app/views/layouts/_messages.html.erb
<div class="container mt-3">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to 'FORMS', users_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Users', users_path, class: "nav-link" %>
          </li>
          <% if logged_in? %>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %>
            </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
                <%= link_to 'Edit your profile', edit_user_path(current_user), class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Log in', login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', signup_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <p>The following errors below prevented the <%= obj.class.name.downcase %> from being <strong>saved:</strong></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <hr>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
  
<!--
<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="uname">username:</label>
  <input type="text" id="uname" name="uname" placeholder="Username">
  
  <label for="email">email:</label>
  <input type="email" id="email" name="email" placeholder="Enter your email">

  <label for="password">password:</label>
  <input type="password" id="password" name="password" placeholder="Choose your password">

  <input type="submit" value="Submit">
</form> 

<%= form_tag("/users") do %>
    <%= label_tag 'username' %>
    <%= text_field_tag(:username) %><br/>
    <%= label_tag 'email' %>
    <%= text_field_tag(:email) %><br/>
    <%= label_tag 'password' %>
    <%= password_field_tag 'password' %><br/>
    <%= submit_tag 'Submit'%>
<% end %>

<%= form_for @user do |f| %>
   
    <%= label(:username, "Username: ") %>
    <%= f.text_field :username %><br/>
    <%= label(:email, "Email: ") %>
    <%= f.text_field :email %><br/>
    <%= label(:password,"Password: ") %>
    <%= f.password_field :password %><br/>
    <%= f.submit "submit" %>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group">
    <label for="username"><%= f.label :username %></label>
    <%= f.text_field :username, class: "form-control shadow rounded", id: "username", placeholder: "Enter a username" %>
    <small class="form-text text-muted">Enter your username</small>
  </div>
  <div class="form-group">
    <label for="email"><%= f.label :email %></label>
    <%= f.email_field :email, class: "form-control shadow rounded", id: "email", placeholder: "Enter your email address" %>
  </div>
  <div class="form-group">
    <label for="password"><%= f.label :password %></label>
    <%= f.password_field :password, class: "form-control shadow rounded", id: "password", placeholder: "Choose a password" %>
  </div>
  <div class="my-3">
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary") %>
  </div>
<% end %>
-->
<%= render 'shared/errors', obj: @user %>
<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group">
    <label for="username"><%= f.label :username %></label>
    <%= f.text_field :username, class: "form-control shadow rounded", id: "username", placeholder: "Enter a username" %>
    <small class="form-text text-muted">Enter your username</small>
  </div>
  <div class="form-group">
    <label for="email"><%= f.label :email %></label>
    <%= f.email_field :email, class: "form-control shadow rounded", id: "email", placeholder: "Enter your email address" %>
  </div>
  <div class="form-group">
    <label for="password"><%= f.label :password %></label>
    <%= f.password_field :password, class: "form-control shadow rounded", id: "password", placeholder: "Choose a password" %>
  </div>
  <div class="my-3">
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container" >
  <h1 class="text-center mt-5 mb-4">Edit your profile</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container" >
  <h1 class="text-center mt-5 mb-4">FORMS users</h1>
    <% @users.each do |user| %>
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        <%= link_to user.username, user, class: "link" %>
      </div>
      <div class="card-body">
        <div><%= link_to gravatar_for(user, size: 120), user %></div>
        <div class="my-3">
          <%= link_to 'View profile', user, class: "btn btn-primary" %> 
          <% if logged_in? %>
            <% if user == current_user %>
              <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-info" %> 
            <%end%>
          <% end %>
        </div>
      </div>
      <div class="card-footer text-muted">
        <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container" >
  <h1>Register form</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
  
<div class="container" >
  <h1 class="text-center mt-5 mb-4"><%= @user.username %>'s profile</h1>
  <%= gravatar_for @user, size: 200 %>
</div>